### ISSUE TITLE
Servos not moving - Solved

### ISSUE THREAD

**Issue by migsdigs** [madhephaestus/lx16a-servo#14]
I have a Hiwonder xArm robot arm with an ESP32-S (using a NodeMCU-32S board). I had struggled to get the servos to move and to read/write off the servos. 

In my case it seems as if one of the issues is that the servo IDs were not set correctly or servos had been assigned the same ID. It is essential that the servos are given unique IDs. This can be set using either the GUI tool provided by Hiwonder, or it can be done using the script example provided in this repo ([lx16aSetServoID](https://github.com/madhephaestus/lx16a-servo/tree/master/examples/lx16aSetServoID)). For this, the servos should be plugged individually into the ESP32 and assigned an ID one at a time.

I also found that the ESP32-S board used by Hiwonder is different from the ESP32 used in this repo. It is worth to note that their pin layout is very slightly different and that the documentation provided by Hiwonder is slightly incorrect for the board that they utilise.

If you are using the same robot arm and board as me, and you want to run the servos using ESP32 instead of micropython, as Hiwonder provides, I would suggest first running your servos using one wire mode, which is provided by the [lx16aOneWireESPExample](https://github.com/madhephaestus/lx16a-servo/tree/master/examples/lx16aOneWireESPExample). For this I used IO pin 33 on the ESP, and I have adapted the example for the use of 6 servos in my own [Repo](https://github.com/migsdigs/Hiwonder_xArm_ESP32). 

I have found that reading from all 6 servos can be difficult at times (at times I am only able to get readings from 3), but the author of this repo reported to me that this may be a problem with daisy chaining all 6. It was suggested to plug the servos individually into a bread board, in parallel, rather than daisy chaining them. I have not attempted this yet, and thus cannot verify.

**Comment by madhephaestus** [comment]
thanks for posting this story for others to find and learn from!
