### ISSUE TITLE
Will this work with the newest Arduino Uno R4 Wifi board?

### ISSUE THREAD

**Issue by atommoyer** [madhephaestus/lx16a-servo#17]
I have a set of Hiwonder servos from an XArm kit. I want to have my own controller using my spare Arduino Uno R4 Wifi board.

This seems like a great option to start development from. However, I do not understand the limitations of the 1 pin mode and the notes about the modern toolkits.

Do you expect this to work with the modern Arduino brand boards?

**Comment by madhephaestus** [comment]
One pin mode is a special case of a feature that ESP32 and Teensy boards (not AVR to my knowledge) that allows you to assign the tx and rx to the same pin in the IO crossbar. AVR has assigned pins for peripherals at manufacture time, so they can not be remapped arbitrarily. You should look at the 3 pin buffer chip solution for use on AVR.
