### ISSUE TITLE
readLimits() incorrectly overwrites default servo limits

### ISSUE THREAD

**Issue by solexious** [madhephaestus/lx16a-servo#6]
I've been hunting an issue with my servo, setting it to 9000 only had it move about 1/3 of its way to its end limit. It seemed that the -9000 to 9000 range the library was telling me was incorrect.

I added a serial print to the readLimits() function to check what was being sent from the LX-16A:

```
	void readLimits(){
		uint8_t params[4];
		do{
			if (!_bus->read(LX16A_SERVO_ANGLE_LIMIT_READ, params, 4, _id)) {
				commandOK = false;
			}
			commandOK = true;
			minCentDegrees= ((params[0] | ((uint16_t) params[1] << 8))*24)+staticOffset;
			maxCentDegrees= ((params[2] | ((uint16_t) params[3] << 8))*24)+staticOffset;
			Serial.println(" Min set "+String(minCentDegrees)+" max = "+String(maxCentDegrees));
			if(minCentDegrees<maxCentDegrees){
				maxCentDegrees=9000;
				minCentDegrees=-9000;
			}

			Serial.println(" Min set "+String(minCentDegrees)+" max = "+String(maxCentDegrees));
		}while(!isCommandOk());// this is a calibration and can not be allowed to fail
	}
```

This gave the debug output of:

```
Min set 0 max = 24000
Min set -9000 max = 9000
```

So the servo is reporting it should be 0-24000 but the library is setting this to a different range.

Commenting out the `if(minCentDegrees<maxCentDegrees){` check keeps the mix max settings from the servo and allows me to use the servo as expected with its correct full range of movement.

This makes me think this check is bugged and should be fixed or removed. But I'm not sure what this check does so don't want to submit a pull request just removing it.

**Comment by madhephaestus** [comment]
yeah, wow, that is totally wrong you are right. It should be checking if min is GREATER than max, and should set 0 and 24000 as the values if that check fails. Its totally wrong...
