### ISSUE TITLE
Hiwonder HTS-35H?

### ISSUE THREAD

**Issue by samuk** [madhephaestus/lx16a-servo#7]
Would this library work with the higher powered bus servos such as

https://www.hiwonder.hk/products/hiwonder-hts-35h-high-voltage-bus-servo-35kg-torque-with-data-feedback?_pos=9&_sid=01a63a64b&_ss=r

**Comment by madhephaestus** [comment]
I can confirm this device is tested as supported

**Comment by samuk** [comment]
Great stuff, thanks! I'll order a couple.
